"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-11 20:31:36.703660
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists'))
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('playlists',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('spotify_owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('collaborative', sa.Boolean(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('managed_by_spotimax', sa.Boolean(), nullable=False),
    sa.Column('managed_kind', sa.String(length=32), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists'))
    )
    op.create_index(op.f('ix_playlists_spotify_owner_id'), 'playlists', ['spotify_owner_id'], unique=False)
    op.create_table('users',
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('product', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('member', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_spotify_id'), 'users', ['spotify_id'], unique=True)
    op.create_table('albums',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('album_type', sa.String(length=16), nullable=True),
    sa.Column('release_date', sa.String(length=10), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('primary_artist_id', sa.String(length=32), nullable=True),
    sa.Column('total_tracks', sa.SmallInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_artist_id'], ['artists.id'], name=op.f('fk_albums_primary_artist_id_artists'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_albums'))
    )
    op.create_index(op.f('ix_albums_name'), 'albums', ['name'], unique=False)
    op.create_index(op.f('ix_albums_primary_artist_id'), 'albums', ['primary_artist_id'], unique=False)
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.String(length=32), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_artist_genres_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_artist_genres_genre_id_genres'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id', name=op.f('pk_artist_genres'))
    )
    op.create_index(op.f('ix_artist_genres_genre_id'), 'artist_genres', ['genre_id'], unique=False)
    op.create_table('automation_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('backup_discover_weekly', 'backup_release_radar', 'weekly_report', 'liked_songs_snapshot', 'auto_purge', 'playlist_archive_monthly', 'sync_playlists', name='automation_kind'), nullable=False),
    sa.Column('cron', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_automation_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_jobs'))
    )
    op.create_index('ix_automation_jobs_user_kind', 'automation_jobs', ['user_id', 'kind'], unique=False)
    op.create_table('banned_artists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.String(length=32), nullable=False),
    sa.Column('artist_name', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_banned_artists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banned_artists')),
    sa.UniqueConstraint('user_id', 'artist_id', name='uq_banned_artist')
    )
    op.create_index(op.f('ix_banned_artists_user_id'), 'banned_artists', ['user_id'], unique=False)
    op.create_table('banned_genres',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pattern', sa.String(length=128), nullable=False),
    sa.Column('match_mode', sa.Enum('exact', 'contains', 'regex', name='match_mode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('apply_skip_guard', sa.Boolean(), nullable=False),
    sa.Column('apply_library_purge', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_banned_genres_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banned_genres')),
    sa.UniqueConstraint('user_id', 'pattern', 'match_mode', name='uq_banned_rule')
    )
    op.create_index(op.f('ix_banned_genres_user_id'), 'banned_genres', ['user_id'], unique=False)
    op.create_table('blacklist_exemptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('artist', 'track', 'album', name='exemption_kind'), nullable=False),
    sa.Column('spotify_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blacklist_exemptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blacklist_exemptions')),
    sa.UniqueConstraint('user_id', 'kind', 'spotify_id', name='uq_exemption')
    )
    op.create_index(op.f('ix_blacklist_exemptions_user_id'), 'blacklist_exemptions', ['user_id'], unique=False)
    op.create_table('friend_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'blocked', name='friend_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.id'], name=op.f('fk_friend_links_friend_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friend_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_links')),
    sa.UniqueConstraint('user_id', 'friend_user_id', name='uq_friend_pair')
    )
    op.create_index(op.f('ix_friend_links_friend_user_id'), 'friend_links', ['friend_user_id'], unique=False)
    op.create_index(op.f('ix_friend_links_user_id'), 'friend_links', ['user_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('files_total', sa.Integer(), nullable=False),
    sa.Column('files_done', sa.Integer(), nullable=False),
    sa.Column('rows_total', sa.BigInteger(), nullable=False),
    sa.Column('rows_inserted', sa.BigInteger(), nullable=False),
    sa.Column('rows_skipped_duplicate', sa.BigInteger(), nullable=False),
    sa.Column('rows_skipped_invalid', sa.BigInteger(), nullable=False),
    sa.Column('earliest_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unresolved_track_uris', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_import_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_index(op.f('ix_import_jobs_user_id'), 'import_jobs', ['user_id'], unique=False)
    op.create_table('milestones',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('total_minutes', 'total_streams', 'artist_streams', 'track_streams', 'album_streams', 'unique_artists', 'unique_tracks', 'listening_streak_days', name='milestone_kind'), nullable=False),
    sa.Column('threshold', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('entity_name', sa.String(length=512), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_at_achievement', sa.BigInteger(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_milestones_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones')),
    sa.UniqueConstraint('user_id', 'kind', 'threshold', 'entity_id', name='uq_milestone_once')
    )
    op.create_index(op.f('ix_milestones_user_id'), 'milestones', ['user_id'], unique=False)
    op.create_table('playlist_backups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('discover_weekly', 'release_radar', 'daily_mix', 'manual', 'pre_purge', 'pre_bulk', name='backup_kind'), nullable=False),
    sa.Column('source_playlist_id', sa.String(length=32), nullable=True),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('week_label', sa.String(length=16), nullable=True),
    sa.Column('track_uris', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('materialized_playlist_id', sa.String(length=32), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_playlist_backups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist_backups'))
    )
    op.create_index('ix_playlist_backups_user_kind', 'playlist_backups', ['user_id', 'kind'], unique=False)
    op.create_table('purge_runs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Enum('liked_songs', 'playlist', 'all_owned_playlists', name='purge_target'), nullable=False),
    sa.Column('target_playlist_id', sa.String(length=32), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('removed_count', sa.Integer(), nullable=False),
    sa.Column('backup_id', sa.UUID(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_purge_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purge_runs'))
    )
    op.create_index(op.f('ix_purge_runs_user_id'), 'purge_runs', ['user_id'], unique=False)
    op.create_table('skip_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.String(length=32), nullable=True),
    sa.Column('track_name', sa.String(length=512), nullable=True),
    sa.Column('artist_id', sa.String(length=32), nullable=True),
    sa.Column('matched_rule', sa.String(length=128), nullable=True),
    sa.Column('matched_genre', sa.String(length=128), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('skipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_skip_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skip_events'))
    )
    op.create_index('ix_skip_events_user_time', 'skip_events', ['user_id', 'detected_at'], unique=False)
    op.create_table('spotify_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_spotify_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_spotify_credentials'))
    )
    op.create_table('stream_hourly_rollups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('streams', sa.Integer(), nullable=False),
    sa.Column('ms_played', sa.BigInteger(), nullable=False),
    sa.Column('unique_tracks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stream_hourly_rollups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'bucket_start', name=op.f('pk_stream_hourly_rollups'))
    )
    op.create_table('sync_cursors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('recently_played', 'liked_songs', 'playlists', 'followed_artists', 'top_items', name='sync_kind'), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_errors', sa.SmallInteger(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_cursors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'kind', name=op.f('pk_sync_cursors'))
    )
    op.create_table('user_playlists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.String(length=32), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_user_playlists_playlist_id_playlists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_playlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id', name=op.f('pk_user_playlists'))
    )
    op.create_index(op.f('ix_user_playlists_playlist_id'), 'user_playlists', ['playlist_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('en', 'fr', name='locale'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('skip_guard_enabled', sa.Boolean(), nullable=False),
    sa.Column('stream_logger_enabled', sa.Boolean(), nullable=False),
    sa.Column('share_stats_with_friends', sa.Boolean(), nullable=False),
    sa.Column('share_stats_globally', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preferences'))
    )
    op.create_table('tool_runs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('automation_job_id', sa.UUID(), nullable=True),
    sa.Column('tool_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('backup_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automation_job_id'], ['automation_jobs.id'], name=op.f('fk_tool_runs_automation_job_id_automation_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tool_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_runs'))
    )
    op.create_index(op.f('ix_tool_runs_tool_key'), 'tool_runs', ['tool_key'], unique=False)
    op.create_index('ix_tool_runs_user_created', 'tool_runs', ['user_id', 'created_at'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('album_id', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.Column('isrc', sa.String(length=16), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_tracks_album_id_albums'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    op.create_index(op.f('ix_tracks_album_id'), 'tracks', ['album_id'], unique=False)
    op.create_index(op.f('ix_tracks_isrc'), 'tracks', ['isrc'], unique=False)
    op.create_index(op.f('ix_tracks_name'), 'tracks', ['name'], unique=False)
    op.create_table('audio_features',
    sa.Column('track_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Enum('spotify', 'reccobeats', 'acousticbrainz', 'user_import', name='audio_feature_source'), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('key', sa.SmallInteger(), nullable=True),
    sa.Column('mode', sa.SmallInteger(), nullable=True),
    sa.Column('time_signature', sa.SmallInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_audio_features_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', name=op.f('pk_audio_features'))
    )
    op.create_table('playlist_tracks',
    sa.Column('playlist_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=32), nullable=True),
    sa.Column('track_uri', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_tracks_playlist_id_playlists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_playlist_tracks_track_id_tracks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('playlist_id', 'position', name=op.f('pk_playlist_tracks'))
    )
    op.create_index('ix_playlist_tracks_track', 'playlist_tracks', ['track_id'], unique=False)
    op.create_table('streams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.String(length=32), nullable=True),
    sa.Column('spotify_track_uri', sa.String(length=64), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ms_played', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('api_poll', 'json_import', 'web_sdk', 'skip_guard', name='stream_source'), nullable=False),
    sa.Column('track_name', sa.String(length=512), nullable=True),
    sa.Column('artist_name', sa.String(length=512), nullable=True),
    sa.Column('album_name', sa.String(length=512), nullable=True),
    sa.Column('context_uri', sa.String(length=128), nullable=True),
    sa.Column('context_type', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('reason_start', sa.String(length=32), nullable=True),
    sa.Column('reason_end', sa.String(length=32), nullable=True),
    sa.Column('shuffle', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('offline', sa.Boolean(), nullable=True),
    sa.Column('incognito', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_streams_track_id_tracks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_streams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streams')),
    sa.UniqueConstraint('user_id', 'played_at', 'spotify_track_uri', name='uq_stream_dedupe')
    )
    op.create_index('ix_streams_user_played', 'streams', ['user_id', 'played_at'], unique=False)
    op.create_index('ix_streams_user_source', 'streams', ['user_id', 'source'], unique=False)
    op.create_index('ix_streams_user_track', 'streams', ['user_id', 'track_id'], unique=False)
    op.create_table('track_artists',
    sa.Column('track_id', sa.String(length=32), nullable=False),
    sa.Column('artist_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_track_artists_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_artists_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'artist_id', name=op.f('pk_track_artists'))
    )
    op.create_index(op.f('ix_track_artists_artist_id'), 'track_artists', ['artist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_artists_artist_id'), table_name='track_artists')
    op.drop_table('track_artists')
    op.drop_index('ix_streams_user_track', table_name='streams')
    op.drop_index('ix_streams_user_source', table_name='streams')
    op.drop_index('ix_streams_user_played', table_name='streams')
    op.drop_table('streams')
    op.drop_index('ix_playlist_tracks_track', table_name='playlist_tracks')
    op.drop_table('playlist_tracks')
    op.drop_table('audio_features')
    op.drop_index(op.f('ix_tracks_name'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_isrc'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_album_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('ix_tool_runs_user_created', table_name='tool_runs')
    op.drop_index(op.f('ix_tool_runs_tool_key'), table_name='tool_runs')
    op.drop_table('tool_runs')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_playlists_playlist_id'), table_name='user_playlists')
    op.drop_table('user_playlists')
    op.drop_table('sync_cursors')
    op.drop_table('stream_hourly_rollups')
    op.drop_table('spotify_credentials')
    op.drop_index('ix_skip_events_user_time', table_name='skip_events')
    op.drop_table('skip_events')
    op.drop_index(op.f('ix_purge_runs_user_id'), table_name='purge_runs')
    op.drop_table('purge_runs')
    op.drop_index('ix_playlist_backups_user_kind', table_name='playlist_backups')
    op.drop_table('playlist_backups')
    op.drop_index(op.f('ix_milestones_user_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_import_jobs_user_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_friend_links_user_id'), table_name='friend_links')
    op.drop_index(op.f('ix_friend_links_friend_user_id'), table_name='friend_links')
    op.drop_table('friend_links')
    op.drop_index(op.f('ix_blacklist_exemptions_user_id'), table_name='blacklist_exemptions')
    op.drop_table('blacklist_exemptions')
    op.drop_index(op.f('ix_banned_genres_user_id'), table_name='banned_genres')
    op.drop_table('banned_genres')
    op.drop_index(op.f('ix_banned_artists_user_id'), table_name='banned_artists')
    op.drop_table('banned_artists')
    op.drop_index('ix_automation_jobs_user_kind', table_name='automation_jobs')
    op.drop_table('automation_jobs')
    op.drop_index(op.f('ix_artist_genres_genre_id'), table_name='artist_genres')
    op.drop_table('artist_genres')
    op.drop_index(op.f('ix_albums_primary_artist_id'), table_name='albums')
    op.drop_index(op.f('ix_albums_name'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_users_spotify_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_playlists_spotify_owner_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
    # Native enum types are not dropped by autogenerate
    op.execute("DROP TYPE IF EXISTS audio_feature_source")
    op.execute("DROP TYPE IF EXISTS automation_kind")
    op.execute("DROP TYPE IF EXISTS backup_kind")
    op.execute("DROP TYPE IF EXISTS exemption_kind")
    op.execute("DROP TYPE IF EXISTS friend_status")
    op.execute("DROP TYPE IF EXISTS job_status")
    op.execute("DROP TYPE IF EXISTS locale")
    op.execute("DROP TYPE IF EXISTS match_mode")
    op.execute("DROP TYPE IF EXISTS milestone_kind")
    op.execute("DROP TYPE IF EXISTS purge_target")
    op.execute("DROP TYPE IF EXISTS stream_source")
    op.execute("DROP TYPE IF EXISTS sync_kind")
    op.execute("DROP TYPE IF EXISTS user_role")
